name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup
        shell: pwsh
        run: |
          irm https://win.rustup.rs -OutFile r.exe
          .\r.exe -y
          "$env:USERPROFILE\.cargo\bin" | Out-File $env:GITHUB_PATH -Append
          npm install -g pake-cli
      
      - name: Build
        shell: pwsh
        run: |
          "$env:USERPROFILE\.cargo\bin" | Out-File $env:GITHUB_PATH -Append
          pake https://goofyvoice.com --name GoofyVoice
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GoofyVoice
          path: src-tauri/target/release/bundle/msi/*.msi
